### ISSUE TITLE
Usage of FlashDecov data

### ISSUE THREAD

**Issue by Dmorgen** [mlocardpaulet/VisioProt-MS#1]
Hi,

How can I adjust either the script or the attached sheet to use the software with FlashDeconv data?
[flashdeconvTest.xlsx](https://github.com/mlocardpaulet/VisioProt-MS/files/4261566/flashdeconvTest.xlsx)

Thanks!
David.

**Comment by mlocardpaulet** [comment]
Dear David,

VisioProt-MS is not yet compatible with the flashdeconv output files.
What you can do for the moment, as a quick fix, is mimic the ".ms1ft"
files. To do that, rename the column headers of the start and end elution
with : "MinElutionTime" and "MaxElutionTime", the mono-isotopic mass field
should be named "MonoMass", and the intensity "ApexIntensity" (it will be
the colour).
Then, save your file as a tab-separated .txt file.
Finally,  manually change its extension from ".txt" too ".ms1ft".

I attach to this email your excel file with a second tab with modified
headers, and the ".ms1ft" file that can be used as input in VisioProt-MS. I
also added the associated plot.

Please let me know if you have any questions.

Marie.

**Comment by Dmorgen** [comment]
Thanks Marie!

D.
